<a href="https://colab.research.google.com/github/ShauryaPrakashVerma/Machine_Learning_Practice/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#MACHINE LEARNING

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3])   # 1D Tensor / Vector (3D Vector)

array([1, 2, 3])

- [1,2,3,4] vector collection of scalars

- 1d Tensor collection of multiple 0d tensors

- matrices collection of vectors

In [ ]:
np.array([1,2])   # 1D Tensor / Vector (2D Vector)

array([1, 2])

# 2D Tensor / Matrices
 - collection of tensors

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])     # 2D Tensor
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.ndim

2

#3D Tensor

In [ ]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
b

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

### similarly we can keep on increasing the dimension of tensors
 - 4D Tensor will be basically a vector of 3D Tensors
 - max in machine learning 5D Tensors



---



## Rank , Axes , Shape , Size

In [ ]:
# Rank = No of dimensions  (a.ndim)
# No of Axis = Rank = No of Dimensions   (They all are the same)

In [ ]:
# Shape (a.shape)   --> in each axis how many items can be saved
# for eg = (3,4)

In [ ]:
# Size --> no of items in a tensor

# trick --> multiply all numbers in the shape

# in scalars the shape is always 1

## Example of 1D Tensor

In [1]:
# [cgpa , iq , state]   ---> this is a 1D Tensor but when represented in a 3d space it works on three axis - x(cgpa), y(iq), z(state), and hence a 3D Vector bcz it depends on 3 axes00